### PR TITLE
Typos on translation

### PR DESCRIPTION
**Pull request by Arkangel12**
Shout-out to [Fabian Varela](https://github.com/FabianVarela) for enhance this translation

### CODE REVIEW

**Comment by rrousselGit** [comment]
Awesome!

Can you remove the `.idea` folder and fix merge conflicts?

**Comment by Arkangel12** [comment]
.idea should be removed now, I didn't notice it was added! 😅  

please let me know if you need anything else, thanks!

**Comment by rrousselGit** [comment]
Sorry for the late reply

Could you fix merge conflicts? Thanks!

**Comment by rrousselGit** [comment]
Perfect thanks!

**Pull request merged**
