### PR TITLE
Spelling and grammar fixes

### PR DESCRIPTION
**Pull request by ThinkDigitalSoftware**

### CODE REVIEW

**Comment by rrousselGit** [comment]
Nice, thanks!

Could you run `flutter format --line-length 120 .` to fix the CI?

**Comment by ThinkDigitalSoftware** [comment]
Sure thing

On Jan 30, 2020 2:33 AM, Remi Rousselet <notifications@github.com> wrote:

Nice, thanks!

Could you run flutter format --line-length 120 . to fix the CI?

**Comment by ThinkDigitalSoftware** [comment]
After doing so, it shows no changes and when committing, no files, except the .idea folder are shown as changed

**Comment by rrousselGit** [comment]
Well, the CI explicit complains about "consumer.dart" though

If you can't find a solution I'll try and take a look later this week

**Comment by ThinkDigitalSoftware** [comment]
I tried formatting it explicitly and got the same result
Screen Shot 2020-01-30 at 11 40 30 AM

**Comment by rrousselGit** [comment]
You may have an outdated version of Flutter?

**Comment by ThinkDigitalSoftware** [comment]
One sec, l need to switch to the PR first.

**Comment by rrousselGit** [comment]
Perfect thanks!

**Comment by ThinkDigitalSoftware** [comment]
No problem

**Comment by tbm98** [comment]
Hi @rrousselGit. why do you use 120 for length code instead of 80 default?

**Comment by rrousselGit** [comment]
Because sometimes it leads to ugly formatting.
Most of the code is with a length of 80, but some are longer for readability.

I'd actually disable the length if possible, but it leads to the opposite effect where dartfmt puts too many things in a single line.

**Pull request merged**
