### PR TITLE
Prepare for a stable, null-safe release

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
Might have to disable https://github.com/rrousselGit/provider/pull/607/checks?check_run_id=1963321063#step:4:653 for this release

**Comment by rrousselGit** [comment]
Thanks!

It'll probably have to wait a week though. I have to finish https://github.com/flutter/devtools/pull/2706 first. I'd like to avoid having to release a 5.1.0 just a few days after 5.0.0

**Comment by kevmoo** [comment]
We'd like to get this out ASAP since it's blocking a lot of other folks from migrating to stable, null-safety.

Any chance we could front-load this?

**Comment by rrousselGit** [comment]
What do you mean by front-load?

**Comment by kevmoo** [comment]
> What do you mean by front-load?

Sorry. It's a random expression from Iowa. It means prioritize it a bit more....if possible.

**Comment by domesticmouse** [comment]
Just adding myself to this PR so I know when to update codelabs that depend on `provider` =)

**Comment by kevmoo** [comment]
@rrousselGit ?

**Comment by devoncarew** [comment]
We might not want to gate this on the DevTools PR; a DevTools with that change likely won't be available to users for at least a month, even after the PR lands.

**Comment by rrousselGit** [comment]
Hum fair point

I'll make a release tomorrow then.

**Pull request merged**
