### PR TITLE
Turkish README.md Add

### PR DESCRIPTION
**Pull request by selim1238**
Turkish translation README.md add.

### CODE REVIEW

**Review by VB10 — APPROVED** [review]

**Comment by VB10** [comment]
@selim1238 thank you for supporting this repo!!!

**Review by asimolpiq — APPROVED** [review]

**Review by mrjake34 — APPROVED** [review]

**Comment by asimolpiq** [comment]
thank u for translate this package

**Review by cydexx — APPROVED** [review]
cool

**Review by eneskutlay — APPROVED** [review]

**Review by zaferguler0 — APPROVED** [review]

**Review by behzodfaiziev — APPROVED** [review]
Thanks for support

**Review by maksatgw — APPROVED** [review]
Looks Nice!

**Comment by mrjake34** [comment]
Great job on translating the README file for the Flutter Provider package! Your contribution is highly appreciated. As an English speaker, I find it extremely helpful to have the documentation available in multiple languages, as it allows a wider audience to access and benefit from the package.

Your translation appears to be accurate and well-written. The terminology and concepts are clearly explained, making it easier for Turkish-speaking developers to understand and use the Flutter Provider package effectively. I can see that you put a lot of effort into ensuring the readability and clarity of the translated text.

Having a translated README file will encourage more developers in the Turkish-speaking community to adopt and contribute to the Flutter Provider package. It will also make it easier for them to troubleshoot issues and find solutions.

Thank you for your valuable contribution to the Flutter community! Your translation work will undoubtedly have a positive impact on the adoption and usage of the Flutter Provider package among Turkish developers. Keep up the great work!

If you have any questions or need further assistance, feel free to reach out. Happy coding!

Best regards,

**Comment by rrousselGit** [comment]
Looking good, thanks!

**Pull request merged**
