### PR TITLE
Usage documentation

### LINKED ISSUE #139: Only the first instance returned by builder of ProxyProvider (ChangeNotifierProxyProvider) is propagated down the tree
Expected behaviour:
1. Every time the floating action button is pushed, `DecCounter`'s decimal value is incremented.
2. `DecCounter` extends `ValueNotifier`, so the change of value causes the builder of `ListenableProxyProvider<DecCounter, HexCounter>()` to be called.
3. In the builder, `HexCounter`, which also extends `ValueNotifier`, is newly instantiated with the decimal value passed in.
4. The value is converted to a hexadecimal number in `HexCounter`.
5. The change is notified and an update of Text should be triggered.

```dart
class DecCounter extends ValueNotifier<int> {
  DecCounter() : super(0);

  void increment() => value++;
}

class HexCounter extends ValueNotifier<String> {
  HexCounter(int decimal) : super(decimal.toRadixString(16));
}
```

```dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MultiProvider(
        providers: [
          ListenableProvider<DecCounter>(
            builder: (_) => DecCounter(),
            dispose: (_, decCounter) => decCounter.dispose(),
          ),
          ListenableProxyProvider<DecCounter, HexCounter>(
            builder: (_, decCounter, __) => HexCounter(decCounter.value),
            dispose: (_, hexCounter) => hexCounter.dispose(),
          ),
        ],
        child: Scaffold(
          body: _CounterView(),
          floatingActionButton: Consumer<DecCounter>(
            builder: (_, counter, __) {
              return FloatingActionButton(
                onPressed: counter.increment,
                child: const Icon(Icons.add),
              );
            },
          ),
        ),
      ),
    );
  }
}

class _CounterView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final counter = Provider.of<HexCounter>(context);

    return Center(
      child: Text(counter.value.toString()),
    );
  }
}
```

This code does not work as I expected. The number on the screen is not incremented.

I tried many changes in my code and managed to get it to work finally by using and returning the existing instance of `HexCounter` that is obtained from the last parameter of the builder.

```diff
 class HexCounter extends ValueNotifier<String> {
-  HexCounter(int decimal) : super(decimal.toRadixString(16));
+  HexCounter() : super('0');
+
+  void setValue(int decimal) {
+    value = decimal.toRadixString(16);
+  }
 }
```

```diff
 ListenableProxyProvider<DecCounter, HexCounter>(
-  builder: (_, decCounter, __) => HexCounter(decCounter.value),
+  initialBuilder: (_) => HexCounter(),
+  builder: (_, decCounter, prevHexCounter) {
+    return prevHexCounter..setValue(decCounter.value);
+  },
   dispose: (_, hexCounter) => hexCounter.dispose(),
 ),
```

It looks like returning different `HexCounter` instances by the builder stops propagation. Am I right in thinking so? Does the builder of `ProxyProvider` / `ChangeNotifierProxyProvider` / `ListenableProxyProvider` have to return the same instance on every rebuild?

If so, it seems the documentation of `ProxyProvider`'s constructor may need a little more detail to prevent misuse.

> As opposed to the builder parameter of Provider, builder may be called more than once.

This misled me to think the builder was allowed to return a new instance every time.

### LINKED ISSUE #171: Improve usage documentation
I am starting to learn about `provider` and it's hard to me to understand the differences and use cases of many of the different providers inside the table at the end of the README.md file. For example:

1. `ListenableProvider` is supposed to listens to a `Listenable`, but as fart as I can see, `Listenable` is just `an object that maintains a list of listeners`, it doesn't trigger any updates, so how will `ListenableProvider`  `ask widgets which depend on it to rebuild whenever the listener is called`, if there are no notification mechanisms in `Listenable`? Same question could be asked for `ValueListenableProvider`.

2. What's the difference between `ValueListenableProvider.value`, `ListenableProvider.value` and `ChangeNotifierProvider.value`?

3. For the sake of completeness, shouldn't `ProxyProvider` and `MultiProvider` also be at the table?

Simple examples, along with more refined documentations, showing those use cases would be more than welcome.

### PR DESCRIPTION
**Pull request by rrousselGit**
fixes #139
closes #171 #170 #142 #182 #136

### CODE REVIEW

**Comment by feinstein** [comment]
I found some English mistakes on the docs, I can't review all the code now, but I will make a list later.

**Comment by feinstein** [comment]
@rrousselGit did you see this?

**Comment by rrousselGit** [comment]
Yes, thanks. I fixed them (although some of these are not mistakes, like the `..foo = foo`)

**Comment by feinstein** [comment]
Ok, I thought if `foo` was an instance variable `.` would be enough.

**Pull request merged**
