### PR TITLE
exposed dispose to FutureProvider

### PR DESCRIPTION
**Pull request by iulian0512**

### CODE REVIEW

**Comment by rrousselGit** [comment]
Hello!

Could you add tests, and showcase how it'd be used?
Because it isn't quite clear for me how that would be useful, since `dispose` wouldn't have access to what is inside the `create` call

**Review by rrousselGit — CHANGES_REQUESTED** [review]
Hello!

Could you add tests, and showcase how it'd be used?
Because it isn't quite clear for me how that would be useful, since dispose wouldn't have access to what is inside the create call

**Comment by rrousselGit** [comment]
Hello!

Do you still plan to work on this?

**Comment by iulian0512** [comment]
yes, but did not had the time to do it. you can close this pr then I will reopen, when I have the time.

**Comment by rrousselGit** [comment]
Perfect thanks!

**Pull request closed without merging**
